### ISSUE TITLE
Loading the non-default file is not working

### ISSUE THREAD

**Issue by djfkahn** [djfkahn/MemberHubDirectoryTools#58]
When a list of file options is presented to the user, and the user does not select the default value, then the program throws an error like this:

> `These are the potential roster files:
> 1) ~$EDSK-8Roster2019-09-07.xlsx
> 2) EDSK-8Roster2019-09-07.xlsx
> 3) Benefits Expense.xlsx
> Enter list number of file or press <enter> to use '~$EDSK-8Roster2019-09-07.xlsx':2
> Traceback (most recent call last):
>   File "menu.py", line 437, in <module>
>     main()
>   File "menu.py", line 433, in main
>     roster    = roster_tools.ReadRoster(map_d)
>   File "/Users/djfkahn/Desktop/DEV/MemberHubDirectoryTools/roster_tools.py", line 92, in ReadRoster
>     file_name = files[file_number-1]
> TypeError: unsupported operand type(s) for -: 'str' and 'int'
> `

**Comment by djfkahn** [comment]
Fixed for roster files and directory files on the first commit of the bugFix branch.

**Comment by djfkahn** [comment]
Addressed the hub_map file on 3rd commit of the bugFixes branch.  Adds assumption that hub map is always documented in 'hub_map.csv', so user does not need to select.
